# Comment that will be sent if an issue is judged to be closed
comment: "This issue is closed because it does not meet our issue template. Please read it."
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# Example 1: Bug report
  - "Describe the bug"
  - "Steps to reproduce"
  - "Expected behavior"
- content:
# Example 2: Feature request
  - "Use case"
  - "Expected behaviour"
  - "Additional context"
# The issue is judged to be legal if it includes all keywords from any of these two configs.
# Or it will be closed by the app.
