version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
      
    steps:
      - checkout
      
      - run:
          name: Saludos
          command: echo Hello, world.
      
      - run:
          name: Imrprime la fecha actual
          command: date
