version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
      
    steps:
      - checkout
      
      - run:
          name: Saludos
          command: echo Hello,world.
          
       - run:
          name: Imprime la fecha actual
          command: date
